## Slicing Strings

In [27]:
import numpy as np

element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


## 1.What is the value of element[:4]? What about element[4:]? Or element[:]?

In [28]:
print (element [:4])
print (element[4:])
print (element [:])

oxyg
en
oxygen


## 2.What is element[-1]? What is element[-2]?

In [29]:
print(element[-1])
print(element[-2])

n
e


## 3.Given those answers, explain what element[1:-1] does.

#### what this does is start from the first index (not zero) and captures everything inbetween and skips the last letter of the string



In [30]:
print(element[1:-1])

xyge


## 4.The expression element[3:3] produces an empty string, i.e., a string that contains no characters. If data holds our array of patient data, what does data[3:3, 4:4] produce? What about data[3:3, :]?

#### all will produce an empty string

In [31]:
print(element[3:3])

## Stacking Arrays

In [32]:
A = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
B = np.hstack([A, A])
print('B = ')
print(B)

B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [34]:
C = np.vstack([A, A])
print('C = ')
print(C)

C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
D = np.delete(A, 1, 1)
print('D = ')
print(D)

D = 
[[1 3]
 [4 6]
 [7 9]]


In [36]:
inflammation = np.loadtxt(fname = 'inflammation-01.csv', delimiter = ',')
print(inflammation)


[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


## Change in Inflammation

In [37]:
npdiff = np.array([ 0,  2,  5,  9, 14])

In [38]:
np.diff(npdiff)

array([2, 3, 4, 5])

## 1. Which axis would it make sense to use this function along?

#### the axis it would make most sense to do the difference along axis 1 because then you will get a difference in inflammation over the days for one patient

In [39]:
np.diff(inflammation, axis=1)
print(inflammation)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


## 2. If the shape of an individual data file is (60, 40) (60 rows and 40 columns), what would the shape of the array be after you run the diff() function and why?

#### From an array that is 60 rows and 40 columns if we used the diff() function on this array, then it would be 60 rows and 39 columns since it removes from axis 1 (left to right on the array).


## 3.How would you find the largest change in inflammation for each patient? Does it matter if the change in inflammation is an increase or a decrease?

#### to find the largest change in inflammation 


#### first find the difference 

In [40]:
diff_inflammation=np.diff(inflammation, axis=1)


#### then get the maximum differences


In [42]:
max_inflammation=np.max(diff_inflammation, axis=1)
print(max_inflammation)

[ 7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.
  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.
  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.]


#### If the change in inflammation decreases, which is likely while subtracting. The next day can have a negative inflammation and would affect finding the largest change in inflammation for each patient as opposed to the largest change from max to min. 


#### the absolute command will give only absolute values

In [43]:
Max_Min=np.abs(max_inflammation)
print(Max_Min)


[ 7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.
  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.
  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.  7. 12. 11.]
